name: Deploy docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs-app/**'
      - 'ember-google-maps/**'
      - 'ember-google-maps-directions/**'
      - '.github/workflows/docs.yml'

concurrency:
  group: deploy-docs
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: wyvox/action-setup-pnpm@c7fb83d1769e0f8f343604b4adc07a010156096d # v2
        with:
          node-version: '22'
      - name: Build the addon packages
        run: >-
          pnpm
          --filter ember-google-maps
          --filter ember-google-maps-directions
          build
      - name: Build docs-app
        run: pnpm --filter docs-app build
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_DOCS_API_KEY }}
      - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: docs-app/.vitepress/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
        id: deployment
